//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnsweredQuestion
    {
        public int ID { get; set; }
        public bool Deleted { get; set; }
        public bool Hide { get; set; }
        public string Answered { get; set; }
        public int QuestionID { get; set; }
        public int PersonID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public System.DateTime EventDate { get; set; }
    
        public virtual AskedQuestion AskedQuestion { get; set; }
        public virtual Person Person { get; set; }
    }
}
