//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.EventDetails = new HashSet<EventDetail>();
            this.HoleUseds = new HashSet<HoleUsed>();
            this.EventLocations = new HashSet<EventLocation>();
            this.Fuckings = new HashSet<Fucking>();
        }
    
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Notes { get; set; }
        public Nullable<int> OverAllRating { get; set; }
        public bool Remove { get; set; }
        public int OrgamNumber { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public Nullable<int> LoadSize { get; set; }
        public Nullable<bool> Squirt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventDetail> EventDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoleUsed> HoleUseds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventLocation> EventLocations { get; set; }
        public virtual Login Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fucking> Fuckings { get; set; }
        public virtual Event Event1 { get; set; }
        public virtual Event Event2 { get; set; }
        public virtual LoadSize LoadSize1 { get; set; }
    }
}
