//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class STIREsult
    {
        public int ID { get; set; }
        public string STI { get; set; }
        public string Result { get; set; }
        public Nullable<int> PersonID { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> ResultsDate { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
