//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STracker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STrackerEntities : DbContext
    {
        public STrackerEntities()
            : base("name=STrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventAction> EventActions { get; set; }
        public virtual DbSet<EventDetail> EventDetails { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<SocalSite> SocalSites { get; set; }
        public virtual DbSet<STIREsult> STIREsults { get; set; }
        public virtual DbSet<Fucking> Fuckings { get; set; }
        public virtual DbSet<Hole> Holes { get; set; }
        public virtual DbSet<HoleUsed> HoleUseds { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<AnsweredQuestion> AnsweredQuestions { get; set; }
        public virtual DbSet<AskedQuestion> AskedQuestions { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
    }
}
